### ISSUE TITLE
Just passed by and saw this

### ISSUE THREAD

**Issue by Jipok** [cg-jl/font-search#1]
> Two weeks ago I wanted to try a new font in my awesome terminal, [alacritty](https://github.com/alacritty/alacritty). But I didn't get the name right for a long time and poor Alacritty couldn't recognise the font I was trying to get it to show.

> ...Fan of simplicity.

You could just do this:
`fc-list | fzf`

**Comment by cg-jl** [comment]
Yeah, I know. Just after finishing the project I found out about `fc-list` and I just `fc-list | rg -i mything` to search for fonts
